### PR TITLE
fix optional param filtering

### LINKED ISSUE #27: Undocumented breaking change between 1.0.0 and 1.1.0
There is an undocumented breaking change between 1.0.0 and 1.1.0 that causes any code that has query parameters appear before any required parameters to fail compilation. The easiest workaround is to reorder the parameters, however that can cause confusion to end users where the type safety may be weaker than in Java (aka TypeScript).

### PR DESCRIPTION
**Pull request by ferozco**
Closes #27.

## Before this PR
There was an issue where the generated services would not compile if they had optional path params and body params

## After this PR

The issue is resolved and we preserve ordering of parameters

### CODE REVIEW

File: conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java [hunk 1]
```diff
@@ -178,10 +177,7 @@ private MethodSpec generateServiceMethod(
         List<MethodSpec> alternateMethods = Lists.newArrayList();
         for (int i = 0; i < queryArgs.size(); i++) {
             alternateMethods.add(createCompatibilityBackfillMethod(
-                    EndpointDefinition.builder()
-                            .from(endpointDef)
-                            .args(Iterables.concat(args, queryArgs.subList(0, i)))
-                    .build(),
+                    endpointDef,
```
Comment (markelliot) [inline conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java:181]: If you don’t filter the params, you need to at least pass `i`, so that the method can filter the defaulted params...

File: conjure-java-core/src/test/resources/test/api/TestService.java.jersey [hunk 2]
```diff
@@ -124,29 +125,40 @@ public interface TestService {
...
 
     @Deprecated
     default int testQueryParams(
             AuthHeader authHeader,
             ResourceIdentifier something,
             ResourceIdentifier implicit,
-            Optional<ResourceIdentifier> optionalMiddle) {
+            Optional<ResourceIdentifier> optionalMiddle,
+            Set<String> setEnd,
+            Optional<ResourceIdentifier> optionalEnd,
```
Comment (markelliot) [inline conjure-java-core/src/test/resources/test/api/TestService.java.jersey]: this shouldn’t be an argument

File: conjure-java-core/src/test/resources/test/api/TestService.java.jersey [hunk 3]
```diff
@@ -155,8 +167,10 @@ public interface TestService {
             ResourceIdentifier something,
             ResourceIdentifier implicit,
             Optional<ResourceIdentifier> optionalMiddle,
-            Set<String> setEnd) {
+            Set<String> setEnd,
+            Optional<ResourceIdentifier> optionalEnd,
```
Comment (markelliot) [inline conjure-java-core/src/test/resources/test/api/TestService.java.jersey]: shouldn’t be an argument

**Review by markelliot — CHANGES_REQUESTED** [review]

File: conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java [hunk 4]
```diff
@@ -195,33 +192,41 @@ private MethodSpec createCompatibilityBackfillMethod(
...
+                extraArgs.stream()
+                        .filter(arg -> arg.getArgName().get().equals(param.name))
+                        .findFirst())
+                .collect(Collectors.toList());
 
         MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder(endpointDef.getEndpointName().get())
                 .addModifiers(Modifier.PUBLIC, Modifier.DEFAULT)
                 .addAnnotation(Deprecated.class)
-                .addParameters(params);
+                .addParameters(IntStream.range(0, sortedParams.size())
```
Comment (markelliot) [inline conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java:207]: Might be clearer to flatMap here?

File: conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java [hunk 5]
```diff
@@ -195,33 +192,41 @@ private MethodSpec createCompatibilityBackfillMethod(
             TypeMapper returnTypeMapper,
             TypeMapper methodTypeMapper,
             List<ArgumentDefinition> extraArgs) {
-        List<ParameterSpec> params = createServiceMethodParameters(endpointDef, methodTypeMapper, false);
+        List<ParameterSpec> sortedParams = createServiceMethodParameters(endpointDef, methodTypeMapper, false);
+        List<Optional<ArgumentDefinition>> sortedMaybeExtraArgs = sortedParams.stream().map(param ->
```
Comment (markelliot) [inline conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java]: Wondering if it’d be better to change the method signature/this is a little gross and probably at least deserves a comment explaining what’s going on.

File: conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java [hunk 6]
```diff
@@ -195,33 +192,41 @@ private MethodSpec createCompatibilityBackfillMethod(
...
-        for (ParameterSpec param : params) {
-            sb.append("$N, ");
-        }
-
-        List<CodeBlock> fillerValues = Lists.newArrayList();
-        for (ArgumentDefinition arg : extraArgs) {
-            sb.append("$L, ");
-            fillerValues.add(arg.getType().accept(TYPE_DEFAULT_VALUE));
-        }
+        List<Object> values = IntStream.range(0, sortedParams.size()).mapToObj(i -> {
```
Comment (markelliot) [inline conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java:216]: Can maybe map over the sortedMaybeExtraArgs list?

**Review by markelliot — APPROVED** [review]
Looks correct, now. Think it might be possible to make the code clearer/left some nits.

**Comment by markelliot** [comment]
Thanks for cleaning up my error.

File: conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java (hunk 4 above)
Comment (ferozco) [reply conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java:207]: Unfortunately we can't since we need the index to check whether the arg exists in `sortedMaybeExtraArgs`

**Review by iamdanfox — APPROVED** [review]
