### PR TITLE
[fix] conjure-undertow supports empty request body empty optionals

### LINKED ISSUE #317: Undertow/Invalid argument with no request body
## What happened?
- have an undertow endpoint with an optional request body (i.e., `Optional<BodyType>`)
- calling the endpoint without passing any request body throws an exception

```
INFO  [2019-04-03T11:01:14.46Z]  com.palantir.conjure.java.undertow.runtime.ConjureExceptionHandler: Error handling request (errorInstanceId: 2e7227fe-9233-4bab-995f-f86d937aee07, errorName: Default:InvalidArgument, throwable1_type: map[actualTypeArguments:[BodyType] rawType:java.util.Optional typeName:java.util.Optional<BodyType>]) (throwable2_message: No content to map due to end-of-input
 at [Source: (io.undertow.io.UndertowInputStream); line: 1, column: 0])
com.palantir.conjure.java.api.errors.ServiceException: ServiceException: INVALID_ARGUMENT (Default:InvalidArgument)
	at com.palantir.conjure.java.undertow.runtime.ConjureExceptionHandler.frameworkException(ConjureExceptionHandler.java:140)
	at com.palantir.conjure.java.undertow.runtime.ConjureExceptionHandler.handleRequest(ConjureExceptionHandler.java:74)
	at com.palantir.tracing.undertow.TracedOperationHandler.handleRequest(TracedOperationHandler.java:68)
	at com.palantir.conjure.java.undertow.runtime.LoggingContextHandler.handleRequest(LoggingContextHandler.java:40)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1871)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1451)
	at java.lang.Thread.run(Thread.java:834)
Caused by: com.palantir.conjure.java.undertow.runtime.FrameworkException: Failed to deserialize response stream. Syntax error?
	at com.palantir.conjure.java.undertow.runtime.FrameworkException.unprocessableEntity(FrameworkException.java:40)
	at com.palantir.conjure.java.undertow.runtime.Encodings$AbstractJacksonEncoding.lambda$deserializer$1(Encodings.java:67)
	at com.palantir.conjure.java.undertow.runtime.ConjureBodySerDe$EncodingDeserializerRegistry.deserialize(ConjureBodySerDe.java:148)

......


Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (io.undertow.io.UndertowInputStream); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:358)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1593)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1185)
	at com.palantir.conjure.java.undertow.runtime.Encodings$AbstractJacksonEncoding.lambda$deserializer$1(Encodings.java:62)
	at com.palantir.conjure.java.undertow.runtime.ConjureBodySerDe$EncodingDeserializerRegistry.deserialize(ConjureBodySerDe.java:148)
```

## What did you want to happen?
When using Jersey instead of undertow, the body is mapped to `null`, so undertow should preserve the same behavior.

The error seems to be coming from this line https://github.com/palantir/conjure-java/blob/develop/conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/Encodings.java#L62

### PR DESCRIPTION
**Pull request by carterkozak**
## Before this PR
Requests with optional body types would only be parsed if JSON `null` was provided, not if the body was not included.

## After this PR
==COMMIT_MSG==
conjure-undertow supports empty request body empty optional values
==COMMIT_MSG==

Fix #317

### CODE REVIEW

**Review by rubenfiszel — APPROVED** [review]

File: conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java [hunk 1]
```diff
@@ -135,17 +136,45 @@ public void serialize(T value, HttpServerExchange exchange) throws IOException {
     private static final class EncodingDeserializerRegistry<T> implements Deserializer<T> {
 
         private final List<EncodingDeserializerContainer<T>> encodings;
+        private final boolean optionalType;
+        private final TypeMarker<T> marker;
```
Comment (carterkozak) [inline conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java:140]: Alternatively we could store `@Nullable private final T optionalType` instead of these two fields. Doesn't make much difference either way.

File: conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java [hunk 2]
```diff
@@ -135,17 +136,44 @@ public void serialize(T value, HttpServerExchange exchange) throws IOException {
...
             this.encodings = encodings.stream()
                     .map(encoding -> new EncodingDeserializerContainer<>(encoding, token))
                     .collect(ImmutableList.toImmutableList());
+            this.optionalType = TypeMarkers.isOptional(token);
+            this.marker = token;
         }
 
         @Override
         public T deserialize(HttpServerExchange exchange) throws IOException {
+            if (optionalType && maybeEmptyBody(exchange)) {
```
Comment (uschi2000) [inline conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java:152]: is it not possible to unit-test this type of stuff?

Comment (carterkozak) [reply conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java:152]: I added two tests for this in `UndertowServiceEteTest`, though they go through the system end-to-end.

Comment (uschi2000) [reply conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java:152]: yeah I saw those, but I find them notoriously hard to read and maintain because the cause/effect connection isn't so clear.

Comment (carterkozak) [reply conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java:152]: Ack, I'll start by adding documentation to the implementation and tests. The unit tests for serialization have been difficult to keep in a state that represents real use. I worry that they make it more difficult to change implementation details, if they break too frequently we'll become desensitized to changing them to make them pass and fail to catch changes that cause bugs.

Comment (uschi2000) [reply conjure-java-undertow-runtime/src/main/java/com/palantir/conjure/java/undertow/runtime/ConjureBodySerDe.java:152]: OK, then the other alternative is to add these test cases to the conjure-verifier suite of tests.
