### PR TITLE
[fix] optional<binary> equivalent to binary for retrofit + Optional<StreamingOutput> for jersey

### LINKED ISSUE #182: Retrofit should handle optional<binary> responses
## What happened?

Retrofit fails to decode optional<binary> because it expects JSON and receives `application/octet-stream` data.

## What did you want to happen?

Retrofit should allow the consumer to stream a response if present.

### PR DESCRIPTION
**Pull request by rubenfiszel**
Fix #182 

For jersey and retrofit, the current behavior of `binary` enables an implicit tri-state with different status code:
- non-empty stream: 200
- empty stream: 200
- null: 204 + null stream on retrofit client

The way forward to achieve a standard behavior with all clients and server is to consider that service that take advantage of this behavior should declare a return type of `optional<binary>` instead. The jersey resource implementation will need to stay the same and keep encoding empty as null.

In this PR, we are making the return type `optional<binary>` being equivalent to `binary` for the retrofit generator and change the jersey generator to return `Optional<StreamingOutput>`.

### CODE REVIEW

File: conjure-java-core/src/main/java/com/palantir/conjure/java/types/ReturnTypeClassNameVisitor.java [hunk 1]
```diff
@@ -58,6 +59,10 @@ public TypeName visitMap(MapType type) {
 
     @Override
     public TypeName visitOptional(OptionalType type) {
+        if (type.getItemType().accept(TypeVisitor.IS_PRIMITIVE)
+                && type.getItemType().accept(TypeVisitor.PRIMITIVE).equals(PrimitiveType.BINARY)) {
+            return delegate.visitPrimitive(PrimitiveType.BINARY);
```
Comment (carterkozak) [inline conjure-java-core/src/main/java/com/palantir/conjure/java/types/ReturnTypeClassNameVisitor.java]: I think we want this.visit, not delegate, since this implementation provides return-type specific binary classes.

Comment (rubenfiszel) [reply conjure-java-core/src/main/java/com/palantir/conjure/java/types/ReturnTypeClassNameVisitor.java]: fixed

File: conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java [hunk 2]
```diff
@@ -169,9 +170,13 @@ private MethodSpec generateServiceMethod(
         }
 
         if (returnType.equals(BINARY_RETURN_TYPE_OUTPUT) || returnType.equals(BINARY_RETURN_TYPE_RESPONSE)) {
-            methodBuilder.addAnnotation(AnnotationSpec.builder(ClassName.get("javax.ws.rs", "Produces"))
-                    .addMember("value", "$T.APPLICATION_OCTET_STREAM", ClassName.get("javax.ws.rs.core", "MediaType"))
-                    .build());
+            methodBuilder
```
Comment (carterkozak) [inline conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java]: Nit: Would be nice to comment that jersey cannot support `Optional<StreamingOutput>`

File: conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java [hunk 3]
```diff
@@ -169,9 +170,13 @@ private MethodSpec generateServiceMethod(
...
+                    .addAnnotation(Nullable.class)
```
Comment (carterkozak) [inline conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java]: Can we avoid adding `Nullable` to non-optional returns?

Comment (rubenfiszel) [reply conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java]: They are nullable technically tho. But being an annotation I guess it's fine.

Comment (carterkozak) [reply conjure-java-core/src/main/java/com/palantir/conjure/java/services/JerseyServiceGenerator.java]: Returning null for those endpoints violates the conjure defined API

**Review by carterkozak — DISMISSED** [review]

**Review by carterkozak — CHANGES_REQUESTED** [review]
Based on https://github.com/palantir/conjure-java-runtime/pull/931 I think we can return optional<StreamingOutput>

**Review by carterkozak — APPROVED** [review]
